# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            iwasasuperhero
url:              http://iwasasuperhero.com

author:
  name:           'James Fleeting'
  url:            https://twitter.com/fleetingftw
  email:          hello@jamesfleeting.com

paginate:         4

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/fleeting/iwasasuperhero.com
