permalink: /:year/:month/:title
auto: true
pygments: true
var:
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
navigation:
- text: Blog
  url: /
- text: About
  url: /about.html
- text: Projects
  url: /projects.html
- text: Archive
  url: /archive.html